name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: pull submodules
      run: git submodule update --init --recursive
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Pull submodules
      run: git submodule update --init --recursive
    - name: Build
      run: cargo build --verbose --release
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-release-binary
        path: target/release/chatrans.exe
